const express = require('express')
const router = express.Router()
const conversationController = require('../controllers/conversation')
const checkAuth = require('../middleware/checkAuth')
const cloudinary = require('../middleware/cloudinary')

router.post('/', checkAuth, conversationController.sendMessage)
router.post('/vocal/:id', checkAuth, conversationController.sendVocalMessage)
router.post('/call/:id', checkAuth, conversationController.logCall)
router.post('/conversation', checkAuth, conversationController.createConversation)
router.patch('/archive/:id', checkAuth, conversationController.archiveConversation)
router.patch('/emoji/:id', checkAuth, conversationController.updateConversationEmoji)
router.patch('/pseudos/:id', checkAuth, conversationController.updateConversationPseudos)
router.patch('/color/:id', checkAuth, conversationController.updateConversationColor)
router.patch('/block/:id', checkAuth, conversationController.blockUserConversation)
router.patch('/unblock/:id', checkAuth, conversationController.unBlockUserConversation)
router.patch('/message/received/:id', checkAuth, conversationController.setMsgReceived)
router.patch('/delete/:id', checkAuth, conversationController.deleteConversation)
router.patch('/message/:convId', checkAuth, conversationController.markAsSeenConversation)
router.get('/byusers/:userid', checkAuth, conversationController.getConversationByUsers)
router.delete('/message/:id', checkAuth, conversationController.deleteMessage)
router.delete('/pseudos/:convId/:userId', checkAuth, conversationController.deleteConversationPseudo)
router.get('/', checkAuth, conversationController.getUserConversations)
router.get('/:converId', checkAuth, conversationController.getConversation)

module.exports = router;